### PR TITLE
update to 1.15.1

### PR DESCRIPTION
**Pull request by yannicklamprecht**
Please create and set the target branch to 1.15.

### CODE REVIEW

**Comment by NathanWolf** [comment]
Thank you! I will test this out when I get a chance.

**Comment by NathanWolf** [comment]
Ah man I messed up and merged into 14 .. I hate how he has these branches set up. I think I'll just make a "master" like a normal person.

**Comment by yannicklamprecht** [comment]
> Ah man I messed up and merged into 14 .. I hate how he has these branches set up. I think I'll just make a "master" like a normal person.

Make a master for latest supported version and create tags for the old versions.

**Comment by NathanWolf** [comment]
Yeah that's how I would do it- tags or branches. I normally use branches since sometimes I have to go back and add fixes to older versions.

I created master and removed the commits from 1.14 (force-pushed, I hate doing that but in this case I think I needed to)

**Comment by NathanWolf** [comment]
Might be missing a spigot repo though? I will look at it more when I get a chance

http://jenkins.elmakers.com/job/PreciousStones/19/console

**Comment by yannicklamprecht** [comment]
> Might be missing a spigot repo though? I will look at it more when I get a chance
> 
> http://jenkins.elmakers.com/job/PreciousStones/19/console

Yes, probably caused by the fact of the local cache.

**Pull request merged**
